You are given the following three documents:

In [54]:
text = ["wookie stormtrooper",
        "wookie wookie wookie stormtrooper stormtrooper stormtrooper",
        "harry potter"]

 * Transform this data into a bag of words representation, with simple counts. How informative is this format? How much information do you have about individual words?

In [55]:
from sklearn.feature_extraction.text import CountVectorizer
CV = CountVectorizer().fit_transform(text).todense()
print(CV)

[[0 0 1 1]
 [0 0 3 3]
 [1 1 0 0]]


 * Calculate Euclidean and cosine distances between each pair of documents. How do these distances relate to your intuition for the documents' similarities?

In [79]:
from sklearn.feature_extraction.text import CountVectorizer
CV = CountVectorizer().fit_transform(text).todense()
def euclidian(doc1,doc2):
    return np.sqrt(np.sum((doc1-doc2)**2))
def cosine(doc1,doc2):
    dot = np.sum(doc1*doc2)
    mag = np.sqrt(np.sum(doc1**2)*np.sum(doc2**2))
    return (dot/mag)

print('Euclidian Distance:')     
for i,doc1 in enumerate(CV):
    for j,doc2 in enumerate(CV):
        if i > j: 
            print('distance between','['+text[i]+']','['+text[j]+']',':',euclidian(np.array(doc1),np.array(doc2)))
print('Cosine Distance:')            
for i,doc1 in enumerate(CV):
    for j,doc2 in enumerate(CV):
        if i > j: 
            print('distance between','['+text[i]+']','['+text[j]+']',':',cosine(np.array(doc1),np.array(doc2)))

Euclidian Distance:
distance between [wookie wookie wookie stormtrooper stormtrooper stormtrooper] [wookie stormtrooper] : 2.82842712475
distance between [harry potter] [wookie stormtrooper] : 2.0
distance between [harry potter] [wookie wookie wookie stormtrooper stormtrooper stormtrooper] : 4.472135955
Cosine Distance:
distance between [wookie wookie wookie stormtrooper stormtrooper stormtrooper] [wookie stormtrooper] : 1.0
distance between [harry potter] [wookie stormtrooper] : 0.0
distance between [harry potter] [wookie wookie wookie stormtrooper stormtrooper stormtrooper] : 0.0


 * Calculate one minus the cosine distance between each pair of de-meaned documents, and the Pearson correlation coefficient between each pair of documents. How are they related? Is this a coincidence? Find a counterexample or prove that there isn't one.

In [80]:
print('1-Cosine Distance:')
for i,doc1 in enumerate(CV):
    for j,doc2 in enumerate(CV):
        if i > j: 
            d1 = np.array(doc1)-np.mean(np.array(doc1))
            d2 = np.array(doc2)-np.mean(np.array(doc2))
            print('distance between','['+text[i]+']','['+text[j]+']',':',1-cosine(d1,d2))
print('Pearson correlation:')
for i,doc1 in enumerate(CV):
    for j,doc2 in enumerate(CV):
        if i > j: 
            d1 = np.array(doc1)
            d2 = np.array(doc2)
            print('distance between','['+text[i]+']','['+text[j]+']',':',np.corrcoef(d1,d2)[0,1])

1-Cosine Distance:
distance between [wookie wookie wookie stormtrooper stormtrooper stormtrooper] [wookie stormtrooper] : 0.0
distance between [harry potter] [wookie stormtrooper] : 2.0
distance between [harry potter] [wookie wookie wookie stormtrooper stormtrooper stormtrooper] : 2.0
Pearson correlation:
distance between [wookie wookie wookie stormtrooper stormtrooper stormtrooper] [wookie stormtrooper] : 1.0
distance between [harry potter] [wookie stormtrooper] : -1.0
distance between [harry potter] [wookie wookie wookie stormtrooper stormtrooper stormtrooper] : -1.0


matrix([[ 0.33333333,  0.33333333,  1.33333333,  1.33333333]])