In [1]:
import numpy as np
import pandas as pd
import os

from sklearn.metrics import accuracy_score
from sklearn.externals import joblib
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix


from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.learning_curve import learning_curve
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_curve
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingClassifier
%matplotlib inline

from __future__ import print_function, division
import pandas as pd 
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
# gensim
from gensim import corpora, models, similarities, matutils
# sklearn
from sklearn import datasets
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.cross_validation import train_test_split
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
import sklearn.metrics.pairwise as smp

from sklearn.decomposition import NMF

/Users/rebeccahyde/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/rebeccahyde/anaconda/lib/python2.7/site-packages/sklearn/learning_curve.py:23: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the functions are moved. This module will be removed in 0.20
  DeprecationWarning)
/Users/rebeccahyde/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a momen

In [36]:
result2 = pd.read_pickle('reviews.pkl')

In [37]:
result2

name  price_level  \
0       Stage Door Deli & Restaurant            2   
1       Stage Door Deli & Restaurant            2   
2       Stage Door Deli & Restaurant            2   
3       Stage Door Deli & Restaurant            2   
4       Stage Door Deli & Restaurant            2   
5                     Dunkin' Donuts            1   
6                     Dunkin' Donuts            1   
7                     Dunkin' Donuts            1   
8                     Dunkin' Donuts            1   
9                     Dunkin' Donuts            1   
10                  NY Pizza Suprema            2   
11                  NY Pizza Suprema            2   
12                  NY Pizza Suprema            2   
13                  NY Pizza Suprema            2   
14                  NY Pizza Suprema            2   
15     Pad Thai ( on 8 Ave / 31 St )            2   
16     Pad Thai ( on 8 Ave / 31 St )            2   
17     Pad Thai ( on 8 Ave / 31 St )            2   
18     Pad Thai ( on 8 Ave / 31 St )            2   
19     Pad Thai ( on 8 Ave / 31 St )            2   
20                    Dunkin' Donuts            1   
21               Brother Jimmy's BBQ            2   
22               Brother Jimmy's BBQ            2   
23               Brother Jimmy's BBQ            2   
24               Brother Jimmy's BBQ            2   
25               Brother Jimmy's BBQ            2   
26                         Taco Bell            1   
27                         Taco Bell            1   
28                         Taco Bell            1   
29                         Taco Bell            1   
...                              ...          ...   
15106          STEM Kitchen & Garden            2   
15107          STEM Kitchen & Garden            2   
15108            Mission Rock Resort            2   
15109            Mission Rock Resort            2   
15110            Mission Rock Resort            2   
15111            Mission Rock Resort            2   
15112            Mission Rock Resort            2   
15113                         Subway            1   
15114                         Subway            1   
15115                         Subway            1   
15116                       The Ramp            1   
15117                       The Ramp            1   
15118                       The Ramp            1   
15119                       The Ramp            1   
15120                       The Ramp            1   
15121         Esposto's Delicatessen            1   
15122         Esposto's Delicatessen            1   
15123         Esposto's Delicatessen            1   
15124         Esposto's Delicatessen            1   
15125         Esposto's Delicatessen            1   
15126                    Moshi Moshi            2   
15127                    Moshi Moshi            2   
15128                    Moshi Moshi            2   
15129                    Moshi Moshi            2   
15130                    Moshi Moshi            2   
15131                 ATWater Tavern            3   
15132                 ATWater Tavern            3   
15133                 ATWater Tavern            3   
15134                 ATWater Tavern            3   
15135                 ATWater Tavern            3   

                                                    text  rating  
0      The female who picked up the phone and took my...       1  
1      We stumbled upon the stage door deli and stage...       5  
2      Great service, and classic old new york atmosp...       3  
3      The worst.once it changed owners.the servings ...       1  
4      Very good place for breakfast with excellent s...       5  
5      quick service even with long lines.  It's also...       5  
6      How good can a Dunks be? Well, it's my wife's ...       3  
7      This is a well staffed Dunkin Donuts which pro...       3  
8      They always take good care of me here, have us...       3  
9                               \nIt's a a dunkin baby!        4  
10     A

In [38]:
result3=result2
result3['rating'] = result3['rating'].map({1:"negative", 2:'negative', 3:'neutral', 4:'positive', 5:'positive'})

In [39]:
result3

name  price_level  \
0       Stage Door Deli & Restaurant            2   
1       Stage Door Deli & Restaurant            2   
2       Stage Door Deli & Restaurant            2   
3       Stage Door Deli & Restaurant            2   
4       Stage Door Deli & Restaurant            2   
5                     Dunkin' Donuts            1   
6                     Dunkin' Donuts            1   
7                     Dunkin' Donuts            1   
8                     Dunkin' Donuts            1   
9                     Dunkin' Donuts            1   
10                  NY Pizza Suprema            2   
11                  NY Pizza Suprema            2   
12                  NY Pizza Suprema            2   
13                  NY Pizza Suprema            2   
14                  NY Pizza Suprema            2   
15     Pad Thai ( on 8 Ave / 31 St )            2   
16     Pad Thai ( on 8 Ave / 31 St )            2   
17     Pad Thai ( on 8 Ave / 31 St )            2   
18     Pad Thai ( on 8 Ave / 31 St )            2   
19     Pad Thai ( on 8 Ave / 31 St )            2   
20                    Dunkin' Donuts            1   
21               Brother Jimmy's BBQ            2   
22               Brother Jimmy's BBQ            2   
23               Brother Jimmy's BBQ            2   
24               Brother Jimmy's BBQ            2   
25               Brother Jimmy's BBQ            2   
26                         Taco Bell            1   
27                         Taco Bell            1   
28                         Taco Bell            1   
29                         Taco Bell            1   
...                              ...          ...   
15106          STEM Kitchen & Garden            2   
15107          STEM Kitchen & Garden            2   
15108            Mission Rock Resort            2   
15109            Mission Rock Resort            2   
15110            Mission Rock Resort            2   
15111            Mission Rock Resort            2   
15112            Mission Rock Resort            2   
15113                         Subway            1   
15114                         Subway            1   
15115                         Subway            1   
15116                       The Ramp            1   
15117                       The Ramp            1   
15118                       The Ramp            1   
15119                       The Ramp            1   
15120                       The Ramp            1   
15121         Esposto's Delicatessen            1   
15122         Esposto's Delicatessen            1   
15123         Esposto's Delicatessen            1   
15124         Esposto's Delicatessen            1   
15125         Esposto's Delicatessen            1   
15126                    Moshi Moshi            2   
15127                    Moshi Moshi            2   
15128                    Moshi Moshi            2   
15129                    Moshi Moshi            2   
15130                    Moshi Moshi            2   
15131                 ATWater Tavern            3   
15132                 ATWater Tavern            3   
15133                 ATWater Tavern            3   
15134                 ATWater Tavern            3   
15135                 ATWater Tavern            3   

                                                    text    rating  
0      The female who picked up the phone and took my...  negative  
1      We stumbled upon the stage door deli and stage...  positive  
2      Great service, and classic old new york atmosp...   neutral  
3      The worst.once it changed owners.the servings ...  negative  
4      Very good place for breakfast with excellent s...  positive  
5      quick service even with long lines.  It's also...  positive  
6      How good can a Dunks be? Well, it's my wife's ...   neutral  
7      This is a well staffed Dunkin Donuts which pro...   neutral  
8      They always take good care of me here, have us...   neutral  
9                               \nIt's a a dunkin baby!

In [40]:
result3["rating"].value_counts()

positive    9591
negative    4016
neutral     1529
Name: rating, dtype: int64

In [41]:
result3 = result3[result3["price_level"]==2]
result3["rating"].value_counts()

positive    4473
negative    1275
neutral      640
Name: rating, dtype: int64

In [42]:

count_vectorizer = CountVectorizer(analyzer='word',
                                  ngram_range=(1, 1), stop_words='english', token_pattern="\\b[a-zA-Z][a-zA-Z]+\\b", min_df=2)

In [43]:
reviews = result3.text
rating = result3.rating
reviews_vecs_cv = count_vectorizer.fit_transform(reviews).transpose()
cv_corpus = matutils.Sparse2Corpus(reviews_vecs_cv)
id2word_cv = dict((v, k) for k, v in count_vectorizer.vocabulary_.iteritems())
# lda_cv = models.LdaModel(corpus_cv, id2word=id2word_cv,  num_topics=3)

In [44]:
# We need to save a mapping (dict) of row id to word (token) for later use by gensim:
tfidf = TfidfVectorizer(analyzer = "word", ngram_range=(1, 2), stop_words='english', token_pattern="\\b[a-zA-Z][a-zA-Z]+\\b", min_df=10)
# Get the vectors
reviews_vecs_tfidf = tfidf.fit_transform(reviews)
tfidf_corpus = matutils.Sparse2Corpus(reviews_vecs_tfidf.transpose())
id2word = dict((v, k) for k, v in tfidf.vocabulary_.iteritems())

In [45]:
reviews_vecs_cv.shape

(6315, 6388)

In [46]:
# Create lda model (equivalent to "fit" in sklearn)
lda= models.LdaModel(cv_corpus, id2word=id2word_cv,  num_topics=50)
lda_corpus=lda[cv_corpus]
reviews_lda = matutils.corpus2dense(lda_corpus, num_terms=50).transpose()
X_train, X_test, y_train, y_test = train_test_split(reviews_lda, rating, 
                                                    test_size=0.33)

In [47]:
modellist = [KNeighborsClassifier(), LogisticRegression(), MultinomialNB(), DecisionTreeClassifier(), RandomForestClassifier(), SVC(), MLPClassifier(alpha=1), AdaBoostClassifier()]
for model in modellist:
    modelfit = model.fit(X_train, y_train)
    modelypred = modelfit.predict(X_test)
    print (str(model).split("(")[0] + ": " + str(round(accuracy_score(y_test, modelypred),3)))
    print (confusion_matrix(y_test, model.predict(X_test)))

KNeighborsClassifier: 0.721
[[ 202   15  195]
 [  52   15  154]
 [ 144   29 1303]]
LogisticRegression: 0.752
[[ 173    0  239]
 [  29    0  192]
 [  62    0 1414]]
MultinomialNB: 0.708
[[  19    0  393]
 [   2    0  219]
 [   2    0 1474]]
DecisionTreeClassifier: 0.665
[[ 198   34  180]
 [  57   23  141]
 [ 195   99 1182]]
RandomForestClassifier: 0.723
[[ 203   10  199]
 [  56   10  155]
 [ 130   34 1312]]
SVC: 0.706
[[  15    0  397]
 [   1    0  220]
 [   3    0 1473]]
MLPClassifier: 0.754
[[ 175    0  237]
 [  28    0  193]
 [  60    0 1416]]
AdaBoostClassifier: 0.75
[[ 206    1  205]
 [  45    5  171]
 [ 100    5 1371]]


In [48]:
lsi= models.LsiModel(tfidf_corpus, id2word=id2word,  num_topics=500)
lsi_corpus=lsi[tfidf_corpus]
reviews_lsi = matutils.corpus2dense(lsi_corpus, num_terms=500).transpose()
X_train, X_test, y_train, y_test = train_test_split(reviews_lsi+1, rating, 
                                                    test_size=0.33)
modellist = [KNeighborsClassifier(), LogisticRegression(), MultinomialNB(), DecisionTreeClassifier(), RandomForestClassifier(), SVC(), MLPClassifier(alpha=1), AdaBoostClassifier()]
for model in modellist:
    modelfit = model.fit(X_train, y_train)
    modelypred = modelfit.predict(X_test)
    print (str(model).split("(")[0] + ": " + str(round(accuracy_score(y_test, modelypred),3)))
    print (confusion_matrix(y_test, model.predict(X_test)))

KNeighborsClassifier: 0.712
[[  50    4  390]
 [   5    8  178]
 [  21    9 1444]]
LogisticRegression: 0.841
[[ 316    1  127]
 [  25   12  154]
 [  24    5 1445]]
MultinomialNB: 0.699
[[   0    0  444]
 [   0    0  191]
 [   0    0 1474]]
DecisionTreeClassifier: 0.686
[[ 251   61  132]
 [  51   31  109]
 [ 162  148 1164]]
RandomForestClassifier: 0.776
[[ 234    8  202]
 [  25    8  158]
 [  59   21 1394]]
SVC: 0.699
[[   0    0  444]
 [   0    0  191]
 [   0    0 1474]]
MLPClassifier: 0.699
[[   0    0  444]
 [   0    0  191]
 [   0    0 1474]]
AdaBoostClassifier: 0.796
[[ 301   33  110]
 [  38   21  132]
 [  77   40 1357]]


In [49]:
nmf = NMF(n_components=500)
nmf_vecs = nmf.fit_transform(reviews_vecs_tfidf)
X_train, X_test, y_train, y_test = train_test_split(nmf_vecs, rating, 
                                                    test_size=0.33)
modellist = [KNeighborsClassifier(), LogisticRegression(), MultinomialNB(), DecisionTreeClassifier(), RandomForestClassifier(), SVC(), MLPClassifier(alpha=1), AdaBoostClassifier()]
for model in modellist:
    modelfit = model.fit(X_train, y_train)
    modelypred = modelfit.predict(X_test)
    print (str(model).split("(")[0] + ": " + str(round(accuracy_score(y_test, modelypred),3)))
    print (confusion_matrix(y_test, model.predict(X_test)))

KNeighborsClassifier: 0.671
[[ 195   17  211]
 [  53   11  146]
 [ 235   31 1210]]
LogisticRegression: 0.701
[[   2    0  421]
 [   0    0  210]
 [   0    0 1476]]
MultinomialNB: 0.7
[[   0    0  423]
 [   0    0  210]
 [   0    0 1476]]
DecisionTreeClassifier: 0.728
[[ 255   47  121]
 [  47   43  120]
 [ 128  110 1238]]
RandomForestClassifier: 0.807
[[ 293   11  119]
 [  40   17  153]
 [  71   13 1392]]
SVC: 0.7
[[   0    0  423]
 [   0    0  210]
 [   0    0 1476]]
MLPClassifier: 0.7
[[   0    0  423]
 [   0    0  210]
 [   0    0 1476]]
AdaBoostClassifier: 0.815
[[ 279   14  130]
 [  50   40  120]
 [  50   26 1400]]


In [50]:
reviews = result3.text
rating = result3.rating
reviews_vecs_cv = count_vectorizer.fit_transform(reviews)
cv_corpus = matutils.Sparse2Corpus(reviews_vecs_cv)
id2word_cv = dict((v, k) for k, v in count_vectorizer.vocabulary_.iteritems())

X_train, X_test, y_train, y_test = train_test_split(reviews_vecs_cv, 
                                                    rating, 
                                                    test_size=0.30)
modellist = [KNeighborsClassifier(), LogisticRegression(), MultinomialNB(), DecisionTreeClassifier(), RandomForestClassifier(), SVC(), MLPClassifier(alpha=1), AdaBoostClassifier()]
for model in modellist:
    modelfit = model.fit(X_train, y_train)
    modelypred = modelfit.predict(X_test)
    print (str(model).split("(")[0] + ": " + str(round(accuracy_score(y_test, modelypred),3)))
    print (confusion_matrix(y_test, model.predict(X_test)))

KNeighborsClassifier: 0.722
[[  43   10  338]
 [   1    9  171]
 [   4    8 1333]]
LogisticRegression: 0.845
[[ 307   23   61]
 [  41   27  113]
 [  24   36 1285]]
MultinomialNB: 0.846
[[ 325   27   39]
 [  41   15  125]
 [  37   26 1282]]
DecisionTreeClassifier: 0.75
[[ 237   53  101]
 [  31   51   99]
 [  82  114 1149]]
RandomForestClassifier: 0.819
[[ 256   15  120]
 [  30   26  125]
 [  30   27 1288]]
SVC: 0.703
[[   2    0  389]
 [   0    0  181]
 [   0    0 1345]]
MLPClassifier: 0.847
[[ 317   23   51]
 [  43   27  111]
 [  28   38 1279]]
AdaBoostClassifier: 0.826
[[ 259   11  121]
 [  37   17  127]
 [  26   12 1307]]


In [51]:
X_train, X_test, y_train, y_test = train_test_split(reviews_vecs_tfidf, 
                                                    rating, 
                                                    test_size=0.30)

In [52]:
modellist = [KNeighborsClassifier(), LogisticRegression(), MultinomialNB(), DecisionTreeClassifier(), RandomForestClassifier(), SVC(), MLPClassifier(alpha=1), AdaBoostClassifier()]

# GaussianNB()
# GradientBoostingClassifier()

In [53]:
for model in modellist:
    modelfit = model.fit(X_train, y_train)
    modelypred = modelfit.predict(X_test)
    print (str(model).split("(")[0] + ": " + str(round(accuracy_score(y_test, modelypred),3)))
    print (confusion_matrix(y_test, model.predict(X_test)))

KNeighborsClassifier: 0.677
[[  21    0  351]
 [  10    1  179]
 [  77    2 1276]]
LogisticRegression: 0.831
[[ 253    2  117]
 [  30    9  151]
 [  20    4 1331]]
MultinomialNB: 0.833
[[ 253    0  119]
 [  28    3  159]
 [  14    0 1341]]
DecisionTreeClassifier: 0.758
[[ 241   24  107]
 [  44   35  111]
 [ 102   75 1178]]
RandomForestClassifier: 0.815
[[ 256    4  112]
 [  36   21  133]
 [  51   18 1286]]
SVC: 0.707
[[   0    0  372]
 [   0    0  190]
 [   0    0 1355]]
MLPClassifier: 0.831
[[ 263    0  109]
 [  41    1  148]
 [  26    0 1329]]
AdaBoostClassifier: 0.817
[[ 248   11  113]
 [  32   35  123]
 [  53   18 1284]]


In [33]:
tfidf = TfidfVectorizer(analyzer = "word", ngram_range=(1, 2), stop_words='english', token_pattern="\\b[a-zA-Z][a-zA-Z]+\\b", min_df=10)
# Get the vectors
reviews_vecs_tfidf = tfidf.fit_transform(reviews)

In [34]:
LR = LogisticRegression()
LR.fit(reviews_vecs_tfidf, rating)
X_test=tfidf.transform(["the restaurant was not ok"])
my_prediction = LR.predict(X_test)

In [150]:
from sklearn.pipeline import Pipeline, FeatureUnion, make_union
model_pipe = Pipeline([
        ("tfidf", tfidf),
        ("model", LogisticRegression())  # Model
        ]).fit(reviews, rating)

In [145]:
model_pipe.predict(reviews[-5:])

array(['positive', 'positive', 'neutral', 'positive', 'positive'], dtype=object)

In [117]:
my_prediction

array(['neutral'], dtype=object)

In [151]:
joblib.dump(model_pipe, 'models/reviewsLR.pkl')

['models/reviewsLR.pkl']

In [152]:
estimator = joblib.load('models/reviewsLR.pkl')

In [157]:
x = estimator.predict(["the restaurant was not ok"])

In [158]:
x

array(['neutral'], dtype=object)