In [1]:
import numpy as np
import pandas as pd
import os

from sklearn.metrics import accuracy_score
from sklearn.externals import joblib
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix


from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.learning_curve import learning_curve
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_curve
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingClassifier
%matplotlib inline

from __future__ import print_function, division
import pandas as pd 
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
# gensim
from gensim import corpora, models, similarities, matutils
# sklearn
from sklearn import datasets
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.cross_validation import train_test_split
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
import sklearn.metrics.pairwise as smp

from sklearn.decomposition import NMF

/Users/rebeccahyde/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/rebeccahyde/anaconda/lib/python2.7/site-packages/sklearn/learning_curve.py:23: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the functions are moved. This module will be removed in 0.20
  DeprecationWarning)
/Users/rebeccahyde/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a momen

In [2]:
result2 = pd.read_pickle('reviews.pkl')

In [3]:
result2

name  price_level  \
0       Stage Door Deli & Restaurant            2   
1       Stage Door Deli & Restaurant            2   
2       Stage Door Deli & Restaurant            2   
3       Stage Door Deli & Restaurant            2   
4       Stage Door Deli & Restaurant            2   
5                     Dunkin' Donuts            1   
6                     Dunkin' Donuts            1   
7                     Dunkin' Donuts            1   
8                     Dunkin' Donuts            1   
9                     Dunkin' Donuts            1   
10                  NY Pizza Suprema            2   
11                  NY Pizza Suprema            2   
12                  NY Pizza Suprema            2   
13                  NY Pizza Suprema            2   
14                  NY Pizza Suprema            2   
15     Pad Thai ( on 8 Ave / 31 St )            2   
16     Pad Thai ( on 8 Ave / 31 St )            2   
17     Pad Thai ( on 8 Ave / 31 St )            2   
18     Pad Thai ( on 8 Ave / 31 St )            2   
19     Pad Thai ( on 8 Ave / 31 St )            2   
20                    Dunkin' Donuts            1   
21               Brother Jimmy's BBQ            2   
22               Brother Jimmy's BBQ            2   
23               Brother Jimmy's BBQ            2   
24               Brother Jimmy's BBQ            2   
25               Brother Jimmy's BBQ            2   
26                         Taco Bell            1   
27                         Taco Bell            1   
28                         Taco Bell            1   
29                         Taco Bell            1   
...                              ...          ...   
15106          STEM Kitchen & Garden            2   
15107          STEM Kitchen & Garden            2   
15108            Mission Rock Resort            2   
15109            Mission Rock Resort            2   
15110            Mission Rock Resort            2   
15111            Mission Rock Resort            2   
15112            Mission Rock Resort            2   
15113                         Subway            1   
15114                         Subway            1   
15115                         Subway            1   
15116                       The Ramp            1   
15117                       The Ramp            1   
15118                       The Ramp            1   
15119                       The Ramp            1   
15120                       The Ramp            1   
15121         Esposto's Delicatessen            1   
15122         Esposto's Delicatessen            1   
15123         Esposto's Delicatessen            1   
15124         Esposto's Delicatessen            1   
15125         Esposto's Delicatessen            1   
15126                    Moshi Moshi            2   
15127                    Moshi Moshi            2   
15128                    Moshi Moshi            2   
15129                    Moshi Moshi            2   
15130                    Moshi Moshi            2   
15131                 ATWater Tavern            3   
15132                 ATWater Tavern            3   
15133                 ATWater Tavern            3   
15134                 ATWater Tavern            3   
15135                 ATWater Tavern            3   

                                                    text  rating  
0      The female who picked up the phone and took my...       1  
1      We stumbled upon the stage door deli and stage...       5  
2      Great service, and classic old new york atmosp...       3  
3      The worst.once it changed owners.the servings ...       1  
4      Very good place for breakfast with excellent s...       5  
5      quick service even with long lines.  It's also...       5  
6      How good can a Dunks be? Well, it's my wife's ...       3  
7      This is a well staffed Dunkin Donuts which pro...       3  
8      They always take good care of me here, have us...       3  
9                               \nIt's a a dunkin baby!        4  
10     A

In [4]:
result3=result2
result3['rating'] = result3['rating'].map({1:"negative", 2:'negative', 3:'neutral', 4:'positive', 5:'positive'})

In [5]:
result3

name  price_level  \
0       Stage Door Deli & Restaurant            2   
1       Stage Door Deli & Restaurant            2   
2       Stage Door Deli & Restaurant            2   
3       Stage Door Deli & Restaurant            2   
4       Stage Door Deli & Restaurant            2   
5                     Dunkin' Donuts            1   
6                     Dunkin' Donuts            1   
7                     Dunkin' Donuts            1   
8                     Dunkin' Donuts            1   
9                     Dunkin' Donuts            1   
10                  NY Pizza Suprema            2   
11                  NY Pizza Suprema            2   
12                  NY Pizza Suprema            2   
13                  NY Pizza Suprema            2   
14                  NY Pizza Suprema            2   
15     Pad Thai ( on 8 Ave / 31 St )            2   
16     Pad Thai ( on 8 Ave / 31 St )            2   
17     Pad Thai ( on 8 Ave / 31 St )            2   
18     Pad Thai ( on 8 Ave / 31 St )            2   
19     Pad Thai ( on 8 Ave / 31 St )            2   
20                    Dunkin' Donuts            1   
21               Brother Jimmy's BBQ            2   
22               Brother Jimmy's BBQ            2   
23               Brother Jimmy's BBQ            2   
24               Brother Jimmy's BBQ            2   
25               Brother Jimmy's BBQ            2   
26                         Taco Bell            1   
27                         Taco Bell            1   
28                         Taco Bell            1   
29                         Taco Bell            1   
...                              ...          ...   
15106          STEM Kitchen & Garden            2   
15107          STEM Kitchen & Garden            2   
15108            Mission Rock Resort            2   
15109            Mission Rock Resort            2   
15110            Mission Rock Resort            2   
15111            Mission Rock Resort            2   
15112            Mission Rock Resort            2   
15113                         Subway            1   
15114                         Subway            1   
15115                         Subway            1   
15116                       The Ramp            1   
15117                       The Ramp            1   
15118                       The Ramp            1   
15119                       The Ramp            1   
15120                       The Ramp            1   
15121         Esposto's Delicatessen            1   
15122         Esposto's Delicatessen            1   
15123         Esposto's Delicatessen            1   
15124         Esposto's Delicatessen            1   
15125         Esposto's Delicatessen            1   
15126                    Moshi Moshi            2   
15127                    Moshi Moshi            2   
15128                    Moshi Moshi            2   
15129                    Moshi Moshi            2   
15130                    Moshi Moshi            2   
15131                 ATWater Tavern            3   
15132                 ATWater Tavern            3   
15133                 ATWater Tavern            3   
15134                 ATWater Tavern            3   
15135                 ATWater Tavern            3   

                                                    text    rating  
0      The female who picked up the phone and took my...  negative  
1      We stumbled upon the stage door deli and stage...  positive  
2      Great service, and classic old new york atmosp...   neutral  
3      The worst.once it changed owners.the servings ...  negative  
4      Very good place for breakfast with excellent s...  positive  
5      quick service even with long lines.  It's also...  positive  
6      How good can a Dunks be? Well, it's my wife's ...   neutral  
7      This is a well staffed Dunkin Donuts which pro...   neutral  
8      They always take good care of me here, have us...   neutral  
9                               \nIt's a a dunkin baby!

In [6]:
result3["rating"].value_counts()

positive    9591
negative    4016
neutral     1529
Name: rating, dtype: int64

In [7]:
result3 = result3[result3["price_level"]==1]
result3["rating"].value_counts()

positive    4294
negative    2599
neutral      791
Name: rating, dtype: int64

In [8]:

count_vectorizer = CountVectorizer(analyzer='word',
                                  ngram_range=(1, 1), stop_words='english', token_pattern="\\b[a-zA-Z][a-zA-Z]+\\b", min_df=2)

In [27]:
reviews = result3.text
rating = result3.rating
reviews_vecs_cv = count_vectorizer.fit_transform(reviews).transpose()
cv_corpus = matutils.Sparse2Corpus(reviews_vecs_cv)
id2word_cv = dict((v, k) for k, v in count_vectorizer.vocabulary_.iteritems())
# lda_cv = models.LdaModel(corpus_cv, id2word=id2word_cv,  num_topics=3)

In [28]:
# We need to save a mapping (dict) of row id to word (token) for later use by gensim:
tfidf = TfidfVectorizer(analyzer = "word", ngram_range=(1, 2), stop_words='english', token_pattern="\\b[a-zA-Z][a-zA-Z]+\\b", min_df=10)
# Get the vectors
reviews_vecs_tfidf = tfidf.fit_transform(reviews)
tfidf_corpus = matutils.Sparse2Corpus(reviews_vecs_tfidf.transpose())
id2word = dict((v, k) for k, v in tfidf.vocabulary_.iteritems())

In [26]:
reviews_vecs_cv.shape

(6127, 7684)

In [25]:
# Create lda model (equivalent to "fit" in sklearn)
lda= models.LdaModel(cv_corpus, id2word=id2word_cv,  num_topics=50)
lda_corpus=lda[cv_corpus]
reviews_lda = matutils.corpus2dense(lda_corpus, num_terms=50).transpose()
X_train, X_test, y_train, y_test = train_test_split(reviews_lda, rating, 
                                                    test_size=0.33)

In [29]:
modellist = [KNeighborsClassifier(), LogisticRegression(), MultinomialNB(), DecisionTreeClassifier(), RandomForestClassifier(), SVC(), MLPClassifier(alpha=1), AdaBoostClassifier()]
for model in modellist:
    modelfit = model.fit(X_train, y_train)
    modelypred = modelfit.predict(X_test)
    print (str(model).split("(")[0] + ": " + str(round(accuracy_score(y_test, modelypred),3)))
    print (confusion_matrix(y_test, model.predict(X_test)))

KNeighborsClassifier: 0.663
[[ 589   39  232]
 [  79    9  140]
 [ 276   88 1084]]
LogisticRegression: 0.744
[[ 622    0  238]
 [  67    0  161]
 [ 183    0 1265]]
MultinomialNB: 0.731
[[ 480    0  380]
 [  34    0  194]
 [  75    0 1373]]
DecisionTreeClassifier: 0.63
[[ 538   88  234]
 [  73   30  125]
 [ 267  151 1030]]
RandomForestClassifier: 0.695
[[ 599   15  246]
 [  72   14  142]
 [ 243   55 1150]]
SVC: 0.701
[[ 400    0  460]
 [  28    0  200]
 [  69    0 1379]]
MLPClassifier: 0.744
[[ 618    0  242]
 [  67    0  161]
 [ 179    0 1269]]
AdaBoostClassifier: 0.733
[[ 618    2  240]
 [  59    0  169]
 [ 203    3 1242]]


In [51]:
lsi= models.LsiModel(tfidf_corpus, id2word=id2word,  num_topics=500)
lsi_corpus=lsi[tfidf_corpus]
reviews_lsi = matutils.corpus2dense(lsi_corpus, num_terms=500).transpose()
X_train, X_test, y_train, y_test = train_test_split(reviews_lsi+1, rating, 
                                                    test_size=0.33)
modellist = [KNeighborsClassifier(), LogisticRegression(), MultinomialNB(), DecisionTreeClassifier(), RandomForestClassifier(), SVC(), MLPClassifier(alpha=1), AdaBoostClassifier()]
for model in modellist:
    modelfit = model.fit(X_train, y_train)
    modelypred = modelfit.predict(X_test)
    print (str(model).split("(")[0] + ": " + str(round(accuracy_score(y_test, modelypred),3)))
    print (confusion_matrix(y_test, model.predict(X_test)))

KNeighborsClassifier: 0.676
[[ 362   26  922]
 [  58   43  386]
 [ 151   73 2974]]
LogisticRegression: 0.842
[[1077   10  223]
 [ 123   40  324]
 [  93   14 3091]]
MultinomialNB: 0.64
[[   0    0 1310]
 [   0    0  487]
 [   0    0 3198]]
DecisionTreeClassifier: 0.696
[[ 867  135  308]
 [ 132   82  273]
 [ 355  314 2529]]
RandomForestClassifier: 0.755
[[ 825   23  462]
 [ 107   17  363]
 [ 218   50 2930]]
SVC: 0.64
[[   0    0 1310]
 [   0    0  487]
 [   0    0 3198]]
MLPClassifier: 0.79
[[1203    0  107]
 [ 224    0  263]
 [ 455    0 2743]]
AdaBoostClassifier: 0.807
[[1034   20  256]
 [ 134   30  323]
 [ 208   23 2967]]


In [21]:
nmf = NMF(n_components=500)
nmf_vecs = nmf.fit_transform(reviews_vecs_tfidf)
X_train, X_test, y_train, y_test = train_test_split(nmf_vecs, rating, 
                                                    test_size=0.33)
modellist = [KNeighborsClassifier(), LogisticRegression(), MultinomialNB(), DecisionTreeClassifier(), RandomForestClassifier(), SVC(), MLPClassifier(alpha=1), AdaBoostClassifier()]
for model in modellist:
    modelfit = model.fit(X_train, y_train)
    modelypred = modelfit.predict(X_test)
    print (str(model).split("(")[0] + ": " + str(round(accuracy_score(y_test, modelypred),3)))
    print (confusion_matrix(y_test, model.predict(X_test)))

KNeighborsClassifier: 0.677
[[ 822   47  480]
 [ 149   43  324]
 [ 523   91 2516]]
LogisticRegression: 0.668
[[ 240    0 1109]
 [  16    0  500]
 [  35    0 3095]]
MultinomialNB: 0.628
[[   8    0 1341]
 [   0    0  516]
 [   1    0 3129]]
DecisionTreeClassifier: 0.717
[[ 899  153  297]
 [ 119  111  286]
 [ 311  248 2571]]
RandomForestClassifier: 0.787
[[1019   23  307]
 [ 127   41  348]
 [ 221   39 2870]]
SVC: 0.627
[[   0    0 1349]
 [   0    0  516]
 [   0    0 3130]]
MLPClassifier: 0.635
[[  45    0 1304]
 [   1    0  515]
 [   4    0 3126]]
AdaBoostClassifier: 0.8
[[1039   25  285]
 [ 122   70  324]
 [ 195   46 2889]]


In [22]:

X_train, X_test, y_train, y_test = train_test_split(reviews_vecs_cv, 
                                                    rating, 
                                                    test_size=0.30)
modellist = [KNeighborsClassifier(), LogisticRegression(), MultinomialNB(), DecisionTreeClassifier(), RandomForestClassifier(), SVC(), MLPClassifier(alpha=1), AdaBoostClassifier()]
for model in modellist:
    modelfit = model.fit(X_train, y_train)
    modelypred = modelfit.predict(X_test)
    print (str(model).split("(")[0] + ": " + str(round(accuracy_score(y_test, modelypred),3)))
    print (confusion_matrix(y_test, model.predict(X_test)))

KNeighborsClassifier: 0.715
[[ 403   31  735]
 [  35   30  384]
 [  67   40 2816]]
LogisticRegression: 0.832
[[ 937   61  171]
 [  95   91  263]
 [  88   83 2752]]
MultinomialNB: 0.818
[[ 966   69  134]
 [ 111   56  282]
 [ 159   70 2694]]
DecisionTreeClassifier: 0.754
[[ 824   86  259]
 [ 103   95  251]
 [ 202  214 2507]]
RandomForestClassifier: 0.806
[[ 906   19  244]
 [ 104   38  307]
 [ 159   46 2718]]
SVC: 0.66
[[  78    0 1091]
 [   1    0  448]
 [   2    0 2921]]
MLPClassifier: 0.834
[[ 925   52  192]
 [  93   81  275]
 [  75   65 2783]]
AdaBoostClassifier: 0.803
[[ 814   17  338]
 [  87   43  319]
 [ 102   32 2789]]


In [30]:
X_train, X_test, y_train, y_test = train_test_split(reviews_vecs_tfidf, 
                                                    rating, 
                                                    test_size=0.30)

In [31]:
modellist = [KNeighborsClassifier(), LogisticRegression(), MultinomialNB(), DecisionTreeClassifier(), RandomForestClassifier(), SVC(), MLPClassifier(alpha=1), AdaBoostClassifier()]

# GaussianNB()
# GradientBoostingClassifier()

In [32]:
for model in modellist:
    modelfit = model.fit(X_train, y_train)
    modelypred = modelfit.predict(X_test)
    print (str(model).split("(")[0] + ": " + str(round(accuracy_score(y_test, modelypred),3)))
    print (confusion_matrix(y_test, model.predict(X_test)))

KNeighborsClassifier: 0.516
[[192  12 577]
 [ 57   8 183]
 [250  36 991]]
LogisticRegression: 0.825
[[ 677    3  101]
 [  61   10  177]
 [  59    2 1216]]
MultinomialNB: 0.813
[[ 671    0  110]
 [  53    0  195]
 [  73    0 1204]]
DecisionTreeClassifier: 0.735
[[ 584   48  149]
 [  62   32  154]
 [ 116   82 1079]]
RandomForestClassifier: 0.791
[[ 652    6  123]
 [  56   15  177]
 [ 107   13 1157]]
SVC: 0.554
[[   0    0  781]
 [   0    0  248]
 [   0    0 1277]]
MLPClassifier: 0.825
[[ 685    0   96]
 [  67    1  180]
 [  60    0 1217]]
AdaBoostClassifier: 0.761
[[ 549   15  217]
 [  51   33  164]
 [  82   21 1174]]


In [33]:
tfidf = TfidfVectorizer(analyzer = "word", ngram_range=(1, 2), stop_words='english', token_pattern="\\b[a-zA-Z][a-zA-Z]+\\b", min_df=10)
# Get the vectors
reviews_vecs_tfidf = tfidf.fit_transform(reviews)

In [34]:
LR = LogisticRegression()
LR.fit(reviews_vecs_tfidf, rating)
X_test=tfidf.transform(["the restaurant was not ok"])
my_prediction = LR.predict(X_test)

In [150]:
from sklearn.pipeline import Pipeline, FeatureUnion, make_union
model_pipe = Pipeline([
        ("tfidf", tfidf),
        ("model", LogisticRegression())  # Model
        ]).fit(reviews, rating)

In [145]:
model_pipe.predict(reviews[-5:])

array(['positive', 'positive', 'neutral', 'positive', 'positive'], dtype=object)

In [117]:
my_prediction

array(['neutral'], dtype=object)

In [151]:
joblib.dump(model_pipe, 'models/reviewsLR.pkl')

['models/reviewsLR.pkl']

In [152]:
estimator = joblib.load('models/reviewsLR.pkl')

In [157]:
x = estimator.predict(["the restaurant was not ok"])

In [158]:
x

array(['neutral'], dtype=object)